name: Build CloseAll

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.13.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.5

      - name: Install Nuitka
        run: |
          python -m pip install --upgrade pip
          python -m pip install nuitka

      - name: Build .EXE 
        run: |
          python -m nuitka --onefile --standalone --windows-console-mode=disable --assume-yes-for-downloads --output-filename=Close.exe CloseAll.py


      - name: GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.sha }}
          name: Release ${{ github.sha }}
          body: Automated build for commit ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .EXE to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Close.exe
          asset_name: Close.exe
          asset_content_type: application/octet-stream
